apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: o94b9p4tb-python 
  janus-idp.io/tekton: o94b9p4tb-python
  backstage.io/kubernetes-id: o94b9p4tb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o94b9p4tb-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml