apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o94b9p4tb-python
  janus-idp.io/tekton: o94b9p4tb-python
  backstage.io/kubernetes-id: o94b9p4tb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: o94b9p4tb-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
